In [3]:
import pickle as pk
import math
import numpy as np

In [17]:
a = pk.load(open("aval.txt", 'rb'))
# 3 column matrix so 3 degrees (x, y, and z axes)
print(a)
len(a)

[[-1.15704532e-12 -4.37519086e-13  4.90636545e+00]
 [ 9.43566243e-01  4.72028154e-01  4.90363447e+00]
 [ 1.88713249e+00  9.44056306e-01  4.90636572e+00]
 [ 2.83069873e+00  1.41608446e+00  4.90363401e+00]
 [ 3.77426496e+00  1.88811261e+00  4.90636632e+00]
 [ 3.34805138e+00  1.67489420e+00  4.90363334e+00]
 [ 2.40448515e+00  1.20286604e+00  4.90636701e+00]
 [ 1.46091893e+00  7.30837872e-01  4.90363262e+00]
 [ 5.17352708e-01  2.58809704e-01  4.90636776e+00]
 [-4.26213506e-01 -2.13218457e-01  4.90363185e+00]
 [ 4.18958680e-01  2.20389156e-01  4.90636855e+00]
 [-4.11703207e-01 -2.27559846e-01  4.90363106e+00]
 [ 4.16041912e-01  2.13485269e-01  4.90636933e+00]
 [-5.00834048e-01 -3.95312426e-02  4.90363028e+00]
 [ 5.53889451e-01 -6.56974585e-02  4.90637012e+00]
 [-8.24496752e-02 -9.07243562e-01  4.90362949e+00]
 [ 9.37917528e-01 -1.06886834e+00  4.90637092e+00]
 [-1.78874807e-03 -1.54853434e+00  4.90362867e+00]
 [-5.30488007e-02 -1.45327151e+00  4.90637174e+00]
 [-4.44043347e-01 -1.24955162e+

50

In [ ]:
# in calculating pitch and roll angles and throttle, we assumed that the acceleration
# vector is of the form that the axes are ordered as x, y, and z 

In [32]:
# input: acceleration vector
# output: pitch angle as an array
def pitchCalc(a):
    pitchVals = []
    for acc in a:
        # based on the math that pitch=atan2(accx,sqrt(accy^2+accz^2))
        pitchAng = math.atan2(acc[0],math.sqrt(acc[1]**2 + acc[2]**2))
        pitchVals.append([pitchAng])
    return pitchVals

pitch = pitchCalc(a)
print(pitch)
len(pitch)

[[-2.3582534290860677e-13], [0.18924445160952094], [0.36113661587094126], [0.5063702050289332], [0.6226602857077617], [0.573642352598281], [0.4442465634829918], [0.2865607266859822], [0.10491214814525322], [-0.086618596429952], [0.08509875235010712], [-0.08367277078829935], [0.08451433523857926], [-0.10177913668124583], [0.1124059569322106], [-0.016531911643793737], [0.18465446546079148], [-0.00034784793081922024], [-0.010366640084447471], [-0.08752567885221918], [-0.16494281812389133], [-0.24160505160735873], [-0.31587913964631786], [-0.3872965613798489], [-0.3878667049850686], [-0.1933765651584611], [-0.009301996463220275], [0.050398224701101065], [-0.15008699492308566], [0.05857130449001221], [-0.12534780932802692], [-0.014794731210286845], [0.1724038187397314], [0.3444760261507451], [0.3389087920402678], [0.2694550999725114], [0.19562875643868977], [0.1741650064158155], [0.06210853467737418], [-0.12756399407092817], [-0.1716553574958319], [-0.19573500139308556], [-0.269313974314914

50

In [31]:
# input: acceleration vector
# output: roll angle as an array
def rollCalc(a):
    rollVals = []
    for acc in a:
        # based on the math that roll=atan2(accy,sqrt(accx^2+accz^2))
        rollAng = math.atan2(acc[1],math.sqrt(acc[0]**2 + acc[2]**2))
        rollVals.append([rollAng])
    return rollVals

roll = rollCalc(a)
print(roll)
len(roll)

[[-8.917376621211724e-14], [0.0942467580558341], [0.1776942860347833], [0.24507494069851155], [0.29605652687901196], [0.2749390336137187], [0.21669212318851097], [0.1418761405920434], [0.05241088346231194], [-0.043291355913269165], [0.044726274232121936], [-0.0462107729755104], [0.04332913133980511], [-0.008019734112242289], [-0.01330493237161958], [-0.1829207022988404], [-0.21079956787882448], [-0.3058825652024454], [-0.28795179074173394], [-0.24853640092130727], [-0.2071225309159882], [-0.16508752328299026], [-0.1229527654568653], [-0.08184802627860956], [-0.05432028856572963], [-0.08806599791884377], [-0.1935933607737194], [-0.18992713607251055], [-0.12171275227052425], [-0.08295760371889883], [0.026387631732730774], [0.01219080441402359], [-0.08768214358557935], [-0.17639116508376787], [-0.17409877488209488], [-0.13915001126185342], [-0.10145347739394507], [-0.09041023763616249], [-0.03141154291593055], [0.06726149158741684], [0.08911691442893153], [0.10150804144597092], [0.1390784

50

In [34]:
# yaw is defined as 0 as requested
# added the length of the array to be 50 to match those of the pitch and the roll
yaw = np.zeros(50)
print(yaw)
len(50)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]


In [ ]:
# need to calculate throttle